creation_rules:

# KMS service for ${environment}
  # - path_regex: secrets/${environment}/.*
    # kms: '${aws_kms_arn}+${aws_role_arn}'

# KMS service for qa
  - path_regex: secrets/qa/.*
    kms: 'arn:aws:kms:us-east-1:123456789013:key/7de90587-5728-4308-bbd1-163ab8d1d330+arn:aws:iam::123456789013:role/SecretsRole'

# KMS service for prod
  - path_regex: secrets/prod/.*
    kms: 'arn:aws:kms:us-east-1:123456789012:key/6a932ce7-9296-44bd-929e-8f427817c347+arn:aws:iam::123456789012:role/SecretsRole'